site_name: Documentation BBC
site_url: https://tisepse.github.io/Book-By-Click

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
  
  palette:
    # Premier thème (sera celui par défaut)
    - scheme: slate 
      toggle:
        icon: material/brightness-4 
        name: Mode sombre
      primary: indigo
      accent: blue
    
    # Deuxième thème
    - scheme: default  # Mode clair
      toggle:
        icon: material/brightness-7 
        name: Mode clair
      primary: indigo
      accent: blue

repo_url: https://github.com/TISEPSE/Book-By-Click
repo_name: Book-By-Click

nav:
  - Accueil: index.md
  - À propos: about.md

plugins:
  - search

# Ajoutez ceci pour personnaliser le comportement du toggle
extra:
  consent:
    title: Préférences de thème
    description: |
      Choisissez votre thème préféré. Vous pourrez le changer à tout moment.